### PR TITLE
Fix support for courses with extra brackets

### LINKED ISSUE #274: Brackets in course name break course selection
Currently only affects "LAWS6101(O)_S1 Foundations of Australian Law"; class shows up fine, but with the following jQuery error, and does not show up in the "Courses chosen" list.

```
Uncaught Error: Syntax error, unrecognized expression: .lesson[data-name=LAWS6101(O)]
    at Function.at.error (jquery.js:3)
    at mt (jquery.js:3)
    at kt (jquery.js:3)
    at Function.at [as find] (jquery.js:3)
    at init.find (jquery.js:4)
    at new init (jquery.js:3)
    at x (jquery.js:3)
    at Object.add (timetable.js:483)
    at HTMLButtonElement.get (timetable.js:406)
    at HTMLButtonElement.dispatch (jquery.js:4)
```

### PR DESCRIPTION
**Pull request by BishopOfTurkey**
This should fix #274.

### CODE REVIEW

File: js/timetable.js [hunk 1]
```diff
@@ -479,7 +479,10 @@ var Course = {
             // Add course style class.
             for (var i = 1; i <= 6; i++) {
                 if (i === 6 || $('.lesson-style-' + i).length < 1) {
-                    $('.lesson[data-name=' + courseName + ']').parent().addClass('lesson-style-' + i);
+                     //https://stackoverflow.com/questions/6469993/jquery-selector-problem-when-using-a-single-parenthesis
+                    var escapedcourseName = courseName.replace('(', '\\(').replace(')', '\\)')
```
Comment (catmanjan) [inline js/timetable.js]: might just be the github syntax highlighter but this is kind of hard to read, can you put the replaces on new lines? other than that all good
